###
# Авторизация

POST {{baseUrl}}/users/sign
Content-Type: application/json

{
  "login": "test_1",
  "password": "123456"
}

###
# Выход - отмена авториазции для удаления токена

DELETE {{baseUrl}}/users/sign
X-Token: {{token}}
Content-Type: application/json

###
# Свой профиль

GET {{baseUrl}}/users/self
X-Token: dc4bc9c2e5578ff8d0528e237b80e5a9191a9d9958277c01fcf64f99fd8a3ec2
Content-Type: application/json

###

GET {{baseUrl}}/users/6477697210d1060c910caf68
X-Token: dc4bc9c2e5578ff8d0528e237b80e5a9191a9d9958277c01fcf64f99fd8a3ec2
Content-Type: application/json

